apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka-namespace
  labels:
    app: kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
  spec:
    volumes:
    - name: kafka-storage
      persistentVolumeClaim:
        claimName: kafka-pvc
    containers:
    - name: kafka
      image: confluentinc/cp-kafka:latest
      ports:
        - containerPort: 9092
        - containerPort: 9093
      env:       
      - name: KAFKA_BROKER_ID
        value: "0"
      - name: KAFKA_PROCESS_ROLES
        value: "broker,controller"
      - name: KAFKA_NODE_ID
        value: "0"
      - name: KAFKA_LISTENERS
        value: "PLAINTEXT://:9092,CONTROLLER://:9093"
      - name: KAFKA_CONTROLLER_QUORUM_VOTERS
        value: "0@kafka-0.kafka:9093"
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - name: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT://kafka:9092,EXTERNAL://kafka:9093
      - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: "1"
      - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
        value: "1"
      - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
        value: "1"
      - name: KAFKA_LOG_DIRS
        value: "/var/lib/kafka/data"
      volumeMounts:
      - name: kafka-storage
        mountPath: /var/lib/kafka/data
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"