services:
  kafka-1:
    image: bitnami/kafka:3.8.0
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=d8ce1515-401e-44d4-a444-1b6dba479047
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx2G -Xms2G
    volumes:
      - ./server-1.properties:/opt/bitnami/kafka/config/server.properties
    networks:
      - kafka-net
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1"
    #       memory: "2g"
  kafka-2:
    image: bitnami/kafka:3.8.0
    container_name: kafka-2
    ports:
      - "9095:9095"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=d8ce1515-401e-44d4-a444-1b6dba479047
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx2G -Xms2G
    volumes:
      - ./server-2.properties:/opt/bitnami/kafka/config/server.properties
    networks:
      - kafka-net
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1"
    #       memory: "2g"
  kafka-service:
    image: alexflames77/kafka_service:latest
    container_name: kafka-service
    environment:
      - BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9095
    networks:
      - kafka-net
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1"
    #       memory: "2g"
    depends_on:
      - kafka-1
      - kafka-2
networks:
  kafka-net:
    driver: bridge
