services:
  kafka-1:
    image: bitnami/kafka:3.9.0
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=MzkjWRg3T325vL8OxROXjw
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx2G -Xms2G
    volumes:
      - ./server-1.properties:/opt/bitnami/kafka/config/server.properties
      # - ./init-topics.sh:/init-topics.sh
    networks:
      kafka-net:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "kafka-1:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    # command: sh /init-topics.sh
  kafka-2:
    image: bitnami/kafka:3.9.0
    container_name: kafka-2
    ports:
      - "9095:9095"
      - "9094:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=MzkjWRg3T325vL8OxROXjw
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx2G -Xms2G
    volumes:
      - ./server-2.properties:/opt/bitnami/kafka/config/server.properties     
    networks:
      kafka-net:
        ipv4_address: 172.18.0.3
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "kafka-2:9095"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
networks:
  kafka-net:
    external: true

# # Create the external network manually before runnig containers (if not exists)
# docker network create --subnet=172.18.0.0/16 kafka-net

# # Create Kafka topic.
# docker exec -it kafka-1 kafka-topics.sh --create --topic __consumer_offsets --partitions 3 --replication-factor 2 --bootstrap-server 172.18.0.2:9092
# docker exec -it kafka-1 kafka-topics.sh --create --topic video-stream --bootstrap-server 172.18.0.2:9092 --partitions 1 --replication-factor 2
