global:
  scrape_interval: 2s
  evaluation_interval: 2s
  scrape_timeout: 1s

scrape_configs:
  - job_name: 'kafka-clients'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'kafka-client:9080'
          - 'akka-client:9081'
          - 'cats-client:9082'
          - 'fs2-client:9083'
          - 'zio-client:9084'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: application
        regex: '([^:]+):\d+'
        replacement: '$1'
      - source_labels: [__address__]
        target_label: job
        regex: '([^:]+):\d+'
        replacement: '$1'

  - job_name: 'kafka-service'
    static_configs:
      - targets: ['kafka-service:9091']
        labels:
          application: 'kafka-service'
          instance: 'kafka-service:9091'
          job: 'kafka-service'
