global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-client'
    static_configs:
      - targets: ['kafka-client:9080']

  - job_name: 'akka-client'
    static_configs:
      - targets: ['akka-client:9081']

  - job_name: 'cats-client'
    static_configs:
      - targets: ['cats-client:9082']

  - job_name: 'fs2-client'
    static_configs:
      - targets: ['fs2-client:9083']

  - job_name: 'zio-client'
    static_configs:
      - targets: ['zio-client:9084']

  - job_name: 'kafka-service'
    static_configs:
      - targets: ['kafka-service:9091']
