apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
  namespace: spark-namespace
spec:
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:latest
        env:
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      - name: spark-worker
        image: bitnami/spark:latest
        env:
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
    restartPolicy: Never